# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8049de7c0fb8c4b7104eb8866e25c7c1e31c5ab087b05b6268fa011471a38af65b3ccd5786bc69a2d4ddf309c404e9733217e151494a0c722a50884aa6e21105

test:
  secret_key_base: 2537b63f3b38c7426386edee725f1698b62d2ad9a0a157caaa09f0f84fe406ad1ba58d08807d4dce643a6bd68cf8c606fd72432f60e37e4ffe43ad46048f377a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
